apiVersion: batch/v1
kind: Job
metadata:
  name: automation-test-{{ .Release.Name }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  template:
    metadata:
      name: automation-test-{{ .Release.Name }}
    spec:
      containers:
        {{- if not .Values.remoteModle }}
        - name: selenuim-chrome-{{ .Release.Name }}
          image: registry.choerodon.com.cn/c7n-selenium/standalone-chrome:3.141.59
          livenessProbe:
            httpGet:
              host: localhost
              port: 4444
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
        - name: automation-test-{{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $name, $value := .Values.env.open }}
          {{- if not (empty $value) }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          - name: RELEASENAME
            value: {{ .Release.Name }}
          resources:
{{ toYaml .Values.resources | indent 10 }}
      restartPolicy: Never